services:
  mongo:
    container_name: mongo
    image: mongo:4.0.26
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: note
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


  noteapp:
    container_name: noteapp
#    build: .
    image: 158655606547.dkr.ecr.eu-central-1.amazonaws.com/noteapp:latest
    restart: always
    ports:
      - '8000:8000'
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: note
      MONGO_AUTH_SOURCE: admin

  notesfront:
    container_name: notesfront
#    image: notesfront
    image: 158655606547.dkr.ecr.eu-central-1.amazonaws.com/notes-front:latest
    restart: always
    ports:
      - '3000:3000'